name: my_simple_note
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  google_fonts: ^5.1.0
  sqflite: ^2.4.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # Added flutter_launcher_icons package

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"# Path to your Flutter logo image
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
flutter:
  uses-material-design: true
